on: [push]

jobs:
  test_action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest, macos-11, windows-latest, windows-2019]
    name: Install the cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CLI
        uses: ./
        id: install
        with:
          version: 'v0.2.0'
      - name: Test CLI
        run: workos --version
